In [1]:
import pandas as pd
ventas=pd.Series([15,12,21])
ventas

0    15
1    12
2    21
dtype: int64

In [2]:
import pandas as pd
ventas=pd.Series([15,12,21],index=['Ene','Feb','Mar'])
ventas

Ene    15
Feb    12
Mar    21
dtype: int64

In [3]:
ventas[0]

15

In [4]:
#Extraer los valores a partir de una etiqueta, en la fila
ventas['Ene']

15

In [7]:
#Muestra las etiquetas de mi objeto de indices
ventas.index

Index(['Ene', 'Feb', 'Mar'], dtype='object')

In [8]:
#Muestra los valores de la serie
ventas.values

array([15, 12, 21])

In [9]:
#Vamos a dar un nombre a la serie
ventas.name="Ventas 2021"
ventas

Ene    15
Feb    12
Mar    21
Name: Ventas 2021, dtype: int64

In [10]:
ventas.index.name='Meses'
ventas

Meses
Ene    15
Feb    12
Mar    21
Name: Ventas 2021, dtype: int64

In [11]:
ventas.axes

[Index(['Ene', 'Feb', 'Mar'], dtype='object', name='Meses')]

In [13]:
#MEtodo shape retorna el numero de elementos que tiene una serie o 
#un dataframe
ventas.shape

(3,)

In [14]:
#Diccionario para pandas
datos={'manzanas':[3,2,0,1],'naranjas':[0,3,7,2]}
print(datos)

{'manzanas': [3, 2, 0, 1], 'naranjas': [0, 3, 7, 2]}


In [15]:
#Constructor de pandas DataFrama que me permite convertir este diccionario o otra coleccion
#de datos en un dataframe
#Dataframa es un conjunto de series con varios valores de datos
compras=pd.DataFrame(datos)
compras

manzanas  naranjas
0         3         0
1         2         3
2         0         7
3         1         2

In [16]:
#Constructor de pandas DataFrama que me permite convertir este diccionario o otra coleccion
#de datos en un dataframe
#Dataframa es un conjunto de series con varios valores de datos
compras=pd.DataFrame(datos,index=['Juno','Luis','Isabela','Juan'])
compras

manzanas  naranjas
Juno            3         0
Luis            2         3
Isabela         0         7
Juan            1         2

In [18]:
#Acceder a los datos de cada columna
compras['manzanas']

Juno       3
Luis       2
Isabela    0
Juan       1
Name: manzanas, dtype: int64

In [20]:
#Acceder a los datos de cada columna
#Para acceder a los datos de la columna o serie de un dataframa solo es necesario
#llamar el nombre del dataframa, y entre comillas el nombre de la etiquete de la columna
compras['naranjas']

Juno       0
Luis       3
Isabela    7
Juan       2
Name: naranjas, dtype: int64

In [22]:
#Podemos acceder a los indices de las filas y las columnas
#Para las filas
compras.index

Index(['Juno', 'Luis', 'Isabela', 'Juan'], dtype='object')

In [23]:
#Podemos acceder a los indices de las filas y las columnas
#Para las columnas
compras.columns

Index(['manzanas', 'naranjas'], dtype='object')

In [25]:
#Nos retorna los indices de las filas y los indices de las columnas
compras.axes

[Index(['Juno', 'Luis', 'Isabela', 'Juan'], dtype='object'),
 Index(['manzanas', 'naranjas'], dtype='object')]

In [27]:
compras.name='Ventas'
compras.index.name='Clientes'
compras.columns.name='Frutas'
compras

Frutas    manzanas  naranjas
Clientes                    
Juno             3         0
Luis             2         3
Isabela          0         7
Juan             1         2

In [28]:
#Podemos ver los valores de un dataframe que va a visular una matris de valores similar a numpy

compras.values

array([[3, 0],
       [2, 3],
       [0, 7],
       [1, 2]])

In [29]:
#Metodo shape permite ver la dimension de un dataframa
compras.shape

(4, 2)

In [31]:
#Creacion de una serie
#Por defecto, si no se pasa como argumento el atributo index, pandas va a crear unos
#indices por defecto de 0 a n-1, donde n es el numero de elementos de los datos
s=pd.Series([7,5,1])
s

0    7
1    5
2    1
dtype: int64

In [33]:
#Creacion de una serie
#Por defecto, si no se pasa como argumento el atributo index, pandas va a crear unos
#indices por defecto de 0 a n-1, donde n es el numero de elementos de los datos
#El numero de elementos de los indices deben ser igual al numero de elementos de los datos
s=pd.Series([7,5,1],index=['Ene','Feb','Mar'])
s

Ene    7
Feb    5
Mar    1
dtype: int64

In [34]:
#Creacion de una serie
#Por defecto, si no se pasa como argumento el atributo index, pandas va a crear unos
#indices por defecto de 0 a n-1, donde n es el numero de elementos de los datos
#El numero de elementos de los indices deben ser igual al numero de elementos de los datos
s=pd.Series([7,5,1],index=['Ene','Feb','Mar','Abril'])
s

ValueError: Length of values (3) does not match length of index (4)

In [36]:
#Vamos a crear una serie o columna a partir de un 
#diccionario 
d={'Ene':7,'Feb':14,'Mar':23}
print(d)
print()
s=pd.Series(d)
s

{'Ene': 7, 'Feb': 14, 'Mar': 23}



Ene     7
Feb    14
Mar    23
dtype: int64

In [37]:
#Vamos a crear una serie o columna a partir de un 
#diccionario 
d={'Ene':7,'Feb':14,'Mar':23}
print(d)
print()
s=pd.Series(d,index=['Abr','Mar','Feb','Ene'])
s

{'Ene': 7, 'Feb': 14, 'Mar': 23}



Abr     NaN
Mar    23.0
Feb    14.0
Ene     7.0
dtype: float64

In [44]:
#Dataframe con diccionario
import pandas as pd
datos=[
    {
        'columna1':1,
        'columna2':92
    },
    {
        'columna1':3,
        'columna2':94
    },
    {
        'columna3':'Hola mundo'
    }
]
print(datos)
#Convertir la lista en un dataframe

datos_dataframe=pd.DataFrame(datos,index=['Fila 1','Fila 2','Fila 3'])
datos_dataframe

[{'columna1': 1, 'columna2': 92}, {'columna1': 3, 'columna2': 94}, {'columna3': 'Hola mundo'}]


columna1  columna2    columna3
Fila 1       1.0      92.0         NaN
Fila 2       3.0      94.0         NaN
Fila 3       NaN       NaN  Hola mundo

In [48]:
datos_dataframe.name='DataFrame'
datos_dataframe['columna2']


Fila 1    92.0
Fila 2    94.0
Fila 3     NaN
Name: columna2, dtype: float64

In [50]:
datos_dataframe.values

array([[1.0, 92.0, nan],
       [3.0, 94.0, nan],
       [nan, nan, 'Hola mundo']], dtype=object)

In [45]:
print(type(datos))
print(len(datos))
datos_dataframe.shape

<class 'list'>
3


(3, 3)