In [1]:
var1=True
var2=False
print(var1)
print(var2)

True
False


In [2]:
x=1
if x==1:
    print(x)
else:
    print("adios")

1


In [3]:
x==1

True

In [40]:
import pandas as pd
s=pd.Series([5,2,-3,7,8,4])
s

0    5
1    2
2   -3
3    7
4    8
5    4
dtype: int64

In [7]:
s[[True,False,False,True,True,False]]

0    5
3    7
4    8
dtype: int64

In [13]:
print(s)
lista=s>2
lista

0    5
1    2
2   -3
3    7
4    8
5    4
dtype: int64


0     True
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [12]:
#Filtrar filas de una serie a partir de un condicional
s[s>2]

0    5
3    7
4    8
5    4
dtype: int64

# MEtodo loc

In [14]:
s.loc[[True,False,False,True,True,True]]

0    5
3    7
4    8
5    4
dtype: int64

In [15]:
#El metodo loc tambien permite utilizar condicionales
s.loc[s>2]

0    5
3    7
4    8
5    4
dtype: int64

In [16]:
# Metodo iloc
s.iloc[[True,False,False,True,True,True]]

0    5
3    7
4    8
5    4
dtype: int64

In [18]:
#El metodo iloc no permite pasar condiciones 
s.iloc[s>2]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [19]:
type((s>2).values)

numpy.ndarray

In [21]:
#El atributo values nos permite obtener un array de  numpy de datos booleanas
#con los elementos que cumplan cierta condicion, en este caso s>2
(s>2).values

array([ True, False, False,  True,  True,  True])

In [22]:
s.iloc[(s>2).values]

0    5
3    7
4    8
5    4
dtype: int64

In [28]:
#Los elementos que cumplen la condicion los guardamos en una variable lista
#de tipo array de numpy
lista=(s>2).values
print(lista)
print(type(lista))
s.iloc[lista]

[ True False False  True  True  True]
<class 'numpy.ndarray'>


0    5
3    7
4    8
5    4
dtype: int64

In [30]:
import pandas as pd
s=pd.Series([5,2,-3,7,8,4],index=['a','b','c','d','e','f'])
s

a    5
b    2
c   -3
d    7
e    8
f    4
dtype: int64

# Seleccion mediante indices y etiquetas columnas de una serie

In [36]:
import pandas as pd
import numpy as np
#Arange permite obtener numeros aleatorios de 0 a 18
#Reshape permite obtener una matriz de rango 6x3
df=pd.DataFrame(np.arange(18).reshape([6,3]),
                                     index=['a','b','c','d','e','f'],
                                     columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [38]:
#EL metodo gel_loc en este caso me devuelve la posicion
#de la columna B en el dataframe
df.columns.get_loc('B')

1

In [39]:
#EL metodo gel_indexer devuelve un array con la posicion
#de varias columnas indicadas entre corchetes
df.columns.get_indexer(['A','C'])

array([0, 2])

# Seleccion mediante indices y etiquetas filas de una serie

In [41]:
#EL metodo gel_loc en este caso me devuelve la posicion
#de la columna B en el dataframe
df.index.get_loc('a')

0

In [43]:
#EL metodo gel_indexer devuelve un array con la posicion
#de varias columnas indicadas entre corchetes
df.index.get_indexer(['b','d'])

array([1, 3])

# Realizar consultas mediante los indices y las etiquetas en una serie

In [46]:
#El metodo iloc en este caso esta interceptando los valores de la fila c y la columna 2
df.iloc[df.index.get_loc('c'),2]

8

In [48]:
#Podemos acceder a un rango de datos de una serie
#Accedemos a los valores de la fila 5 y la fila 3
#Ademas, de las columnas C y A
# df.iloc[[Indices_filas],[Indices de las columnas]]

df.iloc[[5,3],df.columns.get_indexer(['C','A'])]

C   A
f  17  15
d  11   9

In [49]:
#Podemos acceder a un rango de datos de una serie
#Accedemos a los valores de la fila 5 y la fila 3
#Ademas, de las columnas C y A
# df.iloc[[Indices_filas],[Indices de las columnas]]

df.iloc[[5,3],[1,2]]

B   C
f  16  17
d  10  11

# Uso de listas de booleanos en un DataFrame

In [50]:
import pandas as pd
import numpy as np
#Arange permite obtener numeros aleatorios de 0 a 18
#Reshape permite obtener una matriz de rango 6x3
df=pd.DataFrame(np.arange(18).reshape([6,3]),
                                     index=['a','b','c','d','e','f'],
                                     columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [53]:
#Filtrar valores de las filas de un dataframe a partir de una lista
#de valores boolenas
mask=[True,False,True,False,False,True]
#Nos muestra unicamente los elementos de las filas que tienen el 
#valor  booleana de True
df[mask]

A   B   C
a   0   1   2
c   6   7   8
f  15  16  17

# Filtrado de datos en un dataframe a partir de una condicion

In [55]:
print(df)
print()
df[df.A>7]

    A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17



A   B   C
d   9  10  11
e  12  13  14
f  15  16  17

In [56]:
print(df)
print()
df_filtrado=df[df.A>7]
df_filtrado

    A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17



A   B   C
d   9  10  11
e  12  13  14
f  15  16  17

In [59]:
#Metodo loc filtrado a partir de una condicion
#Filtrado de los valores de la columna B que cumplan la condicion
#que sean mayor que 6 mediante el metodo loc
df.loc[df.B>6]

A   B   C
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [60]:
#Metodo iloc filtrado a partir de una condicion
#Sale un Error porque no deja filtrar por condiciones
df.iloc[df.B>6]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [62]:
#Metodo loc filtrado a partir de una condicion
#Filtrado de los valores de la columna B que cumplan la condicion
#que sean mayor que 6 mediante el metodo iloc
#El metodo iloc para una condicion toca añadir el metodo values
df.iloc[(df.B>6).values]

A   B   C
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

# Seleccion con indices y etiquetas simultaneamente

In [63]:
import pandas as pd
import numpy as np
#Arange permite obtener numeros aleatorios de 0 a 18
#Reshape permite obtener una matriz de rango 6x3
df=pd.DataFrame(np.arange(18).reshape([6,3]),
                                     index=['a','b','c','d','e','f'],
                                     columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [69]:
df.sample(3,random_state=18)

A   B   C
f  15  16  17
e  12  13  14
b   3   4   5

In [70]:
#Extraer valores de las columnas
df.sample(2,random_state=18,axis=1)

A   B
a   0   1
b   3   4
c   6   7
d   9  10
e  12  13
f  15  16

In [72]:
#Extraer valores de las columnas
#atributo axis 0 hace referencia por defecto a las filas del 
#dataframe, y el axis 1 hace referencia a las columnas 
df.sample(2,random_state=18,axis=0)

A   B   C
f  15  16  17
e  12  13  14

In [75]:
#Podemos utilizar el atributo frac para especificar el porcentaje de
#elementos a extraer de un dataframe
#0.6 hace referencia al 60% de los datos del Dataframe
df.sample(frac=0.6,random_state=18,axis=0)

A   B   C
f  15  16  17
e  12  13  14
b   3   4   5
a   0   1   2

# Metodo pop

Permite eliminar las columnas en un dataframe, elmetodo pop retorna un valor que puede ser almacenado en una variable de una serie

In [78]:
columnas=['A','B','C','D','E']
df=pd.DataFrame(np.arange(15).reshape([3,5]),
               index=['a','b','c'],
               columns=columnas)
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [79]:
columna=df.pop('D')
print(columna)
df

a     3
b     8
c    13
Name: D, dtype: int64


A   B   C   E
a   0   1   2   4
b   5   6   7   9
c  10  11  12  14

# Metodo drop

Permite eliminar una fila de una serie y crear una copia de la serie sin el elemento que fue quitado en con el metodo drop pasado en el argumento

In [82]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
r=s.drop('b')
r

a    1
c    3
d    4
e    5
dtype: int64

In [83]:
s=s.drop('d')
s

a    1
b    2
c    3
e    5
dtype: int64

In [84]:
import numpy as np
#Arange crea unos valores aleatorias de 0 a 18
#Reshape crea una matriz de dimension 6*3
df=pd.DataFrame(np.arange(15).reshape([3,5]),
               index=['a','b','c'],
               columns=['A','B','C','D','E'])
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [86]:
#El metodo drop funciona tanto para las series como para los dataframe
df_filtrado=df.drop('b')
df_filtrado

A   B   C   D   E
a   0   1   2   3   4
c  10  11  12  13  14

In [88]:
#Eliminar una columna en un dataframe a partir del metodo Drop
df_filtrado1=df.drop(columns='B')
df_filtrado1

A   C   D   E
a   0   2   3   4
b   5   7   8   9
c  10  12  13  14

In [89]:
df_filtrado2=df.drop(['a','b'])
df_filtrado2

A   B   C   D   E
c  10  11  12  13  14

In [90]:
import numpy as np
#Arange crea unos valores aleatorias de 0 a 18
#Reshape crea una matriz de dimension 6*3
df=pd.DataFrame(np.arange(15).reshape([3,5]),
               index=['a','b','c'],
               columns=['A','B','C','D','E'])
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [92]:
#Permite editar el Dataframe o la Serie original cuando 
#el valor de inplace esta en True
df.drop(columns='E',inplace=True)
df

A   B   C   D
a   0   1   2   3
b   5   6   7   8
c  10  11  12  13

# Metodo where

In [94]:
s=pd.Series(np.arange(0,10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [97]:
#Filtrar los elementos de la serie que sean numeros pares, los valores que no cumplen la condicion van a 
#tener un valor NaN
s.where(s%2==0)

0    0.0
1    NaN
2    2.0
3    NaN
4    4.0
5    NaN
6    6.0
7    NaN
8    8.0
9    NaN
dtype: float64

In [96]:
#Filtrar los elementos de la serie que sean numeros pares, en este caso los valores que no 
#cumplen con la condicion van a tener un valor -1
s.where(s%2==0,-1)

0    0
1   -1
2    2
3   -1
4    4
5   -1
6    6
7   -1
8    8
9   -1
dtype: int64

In [98]:
lista=s.where(s%2==0,-1)
lista

0    0
1   -1
2    2
3   -1
4    4
5   -1
6    6
7   -1
8    8
9   -1
dtype: int64

# Edicion  de DataFrame

In [102]:
df=pd.DataFrame(np.arange(12).reshape([4,3]),
                index=['a','b','c','d'],
                columns=['A','B','C'])
df

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [103]:
# Modificar un valor de un dataframa con el metodo iloc
# df.iloc[indices_filas, indices_columnas]=Valor_a_cambiar
df.iloc[1,2]=-1
df

A   B   C
a  0   1   2
b  3   4  -1
c  6   7   8
d  9  10  11

In [104]:
df=pd.DataFrame(np.arange(12).reshape([4,3]),
                index=['a','b','c','d'],
                columns=['A','B','C'])
df

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [106]:
#Modificado los valores en la columna B mediante una lista
#los elementos de la lista deben coincidir con el numero de 
#filas del DataFrame
df['B']=[10,20,30,40]
df

A   B   C
a  0  10   2
b  3  20   5
c  6  30   8
d  9  40  11

In [107]:
df['C']=10
df

A   B   C
a  0  10  10
b  3  20  10
c  6  30  10
d  9  40  10

In [112]:
df['B']=6
df

A  B   C
a  0  6  10
b  3  6  10
c  6  6  10
d  9  6  10

In [113]:
#Modificar un rango de valores en el Dataframe
df=pd.DataFrame(np.arange(12).reshape([4,3]),
                index=['a','b','c','d'],
                columns=['A','B','C'])
df

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [114]:
# df.loc[Rango_indices_filas,Rango_indices_columnas]
print(df)
print()
df.loc['b':'c','A':'B']=[[-1,-2],[-3,-4]]
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11



A   B   C
a  0   1   2
b -1  -2   5
c -3  -4   8
d  9  10  11

In [116]:
# df.loc[Rango_indices_filas,Rango_indices_columnas]
#Puedo asignar un solo valor a un rango del dataframe
df.loc['b':'c','A':'B']=[-1]
df

A   B   C
a  0   1   2
b -1  -1   5
c -1  -1   8
d  9  10  11

In [119]:
# df.loc[Rango_indices_filas,Rango_indices_columnas]
#Puedo asignar un solo valor a un rango del dataframe
df.loc['b':'c','A':'B']=-2
df

A   B   C
a  0   1   2
b -2  -2   5
c -2  -2   8
d  9  10  11