In [5]:
import pandas as pd
s=pd.Series([5,2,-3,7,8,4])
s

0    5
1    2
2   -3
3    7
4    8
5    4
dtype: int64

In [6]:
#Utilizado un array de datos booleanos para acceder a las filas de una Serie o Columna
#Estoy utilizando un filtrado de datos por fila
lista=[True,False,False,True,True,False]
s[lista]

0    5
3    7
4    8
dtype: int64

In [9]:
#Puedo utilizar condicionales para acceder a los elementos de una serie 
s>2

0     True
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [8]:
s1=s>2
s1

0     True
1    False
2    False
3     True
4     True
5     True
dtype: bool

In [11]:
#Re realizo un filtro de una serie a partir de la condicion de los valores donde s>2
s[s>2]

0    5
3    7
4    8
5    4
dtype: int64

# Metodo loc

In [12]:
lista=[True,False,False,True,True,False]
s.loc[lista]

0    5
3    7
4    8
dtype: int64

In [14]:
#Filtrado de elementos de una serie donde se cumpla la condicion que los valores 
# de la serie de s en cada fila sean mayores que 2
s.loc[s>2]

0    5
3    7
4    8
5    4
dtype: int64

# Metodo iloc

In [16]:
#MEtodo loc e iloc funcionan de la misma forma con una lista o array de datos booleanos
lista=[True,False,False,True,True,False]
s.iloc[lista]

0    5
3    7
4    8
dtype: int64

In [17]:
s.iloc[s>2]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [19]:
#NOs va a retornar una array de numpy de datos 
#booleanos de los elementos que cumple la condicion
#con valores True
(s>2).values

array([ True, False, False,  True,  True,  True])

In [21]:
#Metodo iloc me permite filtrar por filas a partir de una condicion, pero debo añadir
#el atributo values
s.iloc[(s>2).values]

0    5
3    7
4    8
5    4
dtype: int64

# Seleccion mediante etiquetas e indices 

In [23]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.arange(18).reshape([6,3]))
df

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14
5  15  16  17

In [24]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.arange(18).reshape([6,3]),
               index=['a','b','c','d','e','f'],
               columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [26]:
# MEtodo get_loc para hacer a los indices en este caso de las columnas de un Dataframe
#La columna B esta en la posicion 1
df.columns.get_loc('B')

1

In [27]:
# MEtodo get_loc para hacer a los indices en este caso de las columnas de un Dataframe
#La columna B esta en la posicion 1
df.columns.get_indexer(['A','C'])

array([0, 2])

In [30]:
# MEtodo get_loc para obtener los indices en este caso de las filas de un Dataframe
#La fila f esta en la posicion 5
df.index.get_loc('f')

5

In [31]:
# MEtodo get_loc para obtener los indices en este caso de las filas de un Dataframe
#La fila f esta en la posicion 5
df.index.get_indexer(['a','f'])

array([0, 5])

In [35]:
# df.iloc[Indices_fila,Indice_columna]
#Aqui voy a obtener el valor de la interseccion entre la fila c y la columna 2
print(df)
df.iloc[df.index.get_loc('c'),2]

    A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17


8

In [37]:
#Voy a obtener los valores de las filas [5,3] y las columnas C, A utilizando el metodo
#get_indexer
# df.iloc[[Indices_filas_a_filtrar],[Indices de las columnas a filtrar]]
df.iloc[[5,3],df.columns.get_indexer(['C','A'])]

C   A
f  17  15
d  11   9

In [39]:
#Voy a obtener los valores de las filas [5,3] y las columnas C, A utilizando el metodo
#get_indexer
# df.iloc[[Indices_filas_a_filtrar],[Indices de las columnas a filtrar]]
df.iloc[[5,3],[0,2]]

A   C
f  15  17
d   9  11

# Filtrado de datos en un Dataframe a partir de una lista booleana

In [43]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.arange(18).reshape([6,3]),
               index=['a','b','c','d','e','f'],
               columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [41]:
mask=[True,False,True,False,False,True]
#Filtrar las filas de un dataframe a partir de una lista de datos
#booleanos. PAra ello debo llamar el nombre del dataframa y entre
#corchetes colo la lista de los datos booleanos
df[mask]

A   B   C
a   0   1   2
c   6   7   8
f  15  16  17

# FIltrado de datos a partir de unas condiciones

In [45]:
#Filtrado de datos de la columna donde los elementos cumplan la condicion de que los
#valores sean mayor a 7
df[df.A>7]

A   B   C
d   9  10  11
e  12  13  14
f  15  16  17

In [46]:
# Accion de filtrado mediante el metodo loc utilizando una condicion que los valores
#de la columna B sean mayor a 6
df.loc[df.B>6]

A   B   C
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [49]:
# Accion de filtrado mediante el metodo iloc utilizando una condicion que los valores
#de la columna B sean mayor a 6
df.iloc[(df.B>6).values]

A   B   C
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

# Seleccion aleatoria

In [50]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.arange(18).reshape([6,3]),
               index=['a','b','c','d','e','f'],
               columns=['A','B','C'])
df

A   B   C
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14
f  15  16  17

In [53]:
#Extraer 3 filas de forma aleatoria, sin remplazo  y fijando como semilla
#del generador de numeros aleatorios el 18
df.sample(3,random_state=18)

A   B   C
f  15  16  17
e  12  13  14
b   3   4   5

In [60]:
#Extraer 2 columnas de forma aleatoria, sin remplazo  y fijando como semilla
#del generador de numeros aleatorios el 18
#Axis=1 significa que yo voy a realizar un filtro a partir de las columnas
df.sample(2,random_state=18,axis=1)

A   B
a   0   1
b   3   4
c   6   7
d   9  10
e  12  13
f  15  16

In [70]:
#Extraer mediante el atributo frac un porcentaje de valores en el Dataframe
#Se esta filtrando por columnas, porque axis=1
df.sample(frac=0.6,random_state=18,axis=1)

A   B
a   0   1
b   3   4
c   6   7
d   9  10
e  12  13
f  15  16

In [71]:
#Extraer mediante el atributo frac un porcentaje de valores en el Dataframe
#Se esta filtrando por filas, axis por defecto es igual a 0, no es necesario indicar
#cuando se va a filtrar por filas
df.sample(frac=0.6,random_state=18)

A   B   C
f  15  16  17
e  12  13  14
b   3   4   5
a   0   1   2

# Metodo Pop

Permite extraer una columna de un dataframe y retorna el valor de la columna o serie


In [73]:
df=pd.DataFrame(np.arange(15).reshape([3,5]),
               index=['a','b','c'],
               columns=['A','B','C','D','E'])
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [74]:
#El metodo pop recibe un argumento que hace referencia a la fila que quiero extraer o 
#remover del dataframe
columna=df.pop('B')
print(columna)
df

a     1
b     6
c    11
Name: B, dtype: int64


A   C   D   E
a   0   2   3   4
b   5   7   8   9
c  10  12  13  14

# Metodo Drop
Permite eliminar filas o columnas de una serie o un dataframe

In [75]:
s=pd.Series([1,2,3,4,5],
           index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [76]:
#una caracteristica que tiene el metodo drop es que me devuelve una copia de la estructura
#de datos sin la fila que fue eliminada y se paso como argumento del metodo Drop
r=s.drop('b')
r

a    1
c    3
d    4
e    5
dtype: int64

In [78]:
#una caracteristica que tiene el metodo drop es que me devuelve una copia de la estructura
#de datos sin la fila que fue eliminada y se paso como argumento del metodo Drop
#Eliminacion de dos filas ingresadas en un array como argumento del metodo DROP
r1=s.drop(['a','d'])
r1

b    2
c    3
e    5
dtype: int64

In [80]:
#Atributo inplace=True hace que cuando yo elimine la fila o columna de una serie o un 
#Dataframe se modifica la estructura de datos original y no retorna ningun valor
print(s)
s.drop('e',inplace=True)
s

a    1
b    2
c    3
d    4
e    5
dtype: int64


a    1
b    2
c    3
d    4
dtype: int64

In [84]:
df=pd.DataFrame(np.arange(15).reshape([3,5]),
               index=['a','b','c'],
               columns=['A','B','C','D','E'])
df

A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14

In [86]:
#Metodo drop para eliminar las filas o columnas de un dataframe
df1=df.drop('b')
print(df1)
print()
print(df)


    A   B   C   D   E
a   0   1   2   3   4
c  10  11  12  13  14

    A   B   C   D   E
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14


In [87]:
#Metodo drop para eliminar las filas o columnas de un dataframe
df.drop('b',inplace=True)
print(df)


    A   B   C   D   E
a   0   1   2   3   4
c  10  11  12  13  14


In [89]:
df=df.drop(columns='E')
df

A   B   C   D
a   0   1   2   3
c  10  11  12  13

In [90]:
s=pd.Series(np.arange(0,10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [93]:
#Queremos filtrar los valores de la serie s que sean pares
s.where(s%2==0)

0    0.0
1    NaN
2    2.0
3    NaN
4    4.0
5    NaN
6    6.0
7    NaN
8    8.0
9    NaN
dtype: float64

In [95]:
#Queremos filtrar los valores de la serie s que sean pares
#Los valores que no cumplan la condicion coloque el valor de -1
s.where(s%2==0,-1)

0    0
1   -1
2    2
3   -1
4    4
5   -1
6    6
7   -1
8    8
9   -1
dtype: int64

# Editar un Dataframa mediante metodos loc e iloc

In [96]:
columnas=['A','B','C']
df=pd.DataFrame(np.arange(12).reshape([4,3]),
               index=['a','b','c','d'],
               columns=columnas)
df

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [97]:
#VOy a intersectar una fila y una columna mediante el metodo iloc trabajando con indices
# y voy a modificar su valor, en este caso, modificar el valor en la fila 1 y la columna 2
# df.iloc[indice_fila,indice_columna]=Valor
df.iloc[1,2]=-1
df

A   B   C
a  0   1   2
b  3   4  -1
c  6   7   8
d  9  10  11

In [99]:
#VOy a intersectar una fila y una columna mediante el metodo loc trabajando con etiquetas
# y voy a modificar su valor, en este caso, modificar el valor en la fila 1 y la columna 2
# df.iloc[indice_fila,indice_columna]=Valor
df.loc['a','B']=-1
df

A   B   C
a  0  -1   2
b  3   4  -1
c  6   7   8
d  9  10  11

In [101]:
#ASignar multiples valores a una columna en especifico
columnas=['A','B','C']
df=pd.DataFrame(np.arange(12).reshape([4,3]),
               index=['a','b','c','d'],
               columns=columnas)
print(df)
df['A']=[10,20,30,40]
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11


A   B   C
a  10   1   2
b  20   4   5
c  30   7   8
d  40  10  11

In [102]:
#ASignar un valor a todos los elementos de una columna
columnas=['A','B','C']
df=pd.DataFrame(np.arange(12).reshape([4,3]),
               index=['a','b','c','d'],
               columns=columnas)
print(df)
df['B']=20
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11


A   B   C
a  0  20   2
b  3  20   5
c  6  20   8
d  9  20  11

In [106]:
#ASignar unos valores a un rango de filas y columnas en el dataframe
columnas=['A','B','C']
df=pd.DataFrame(np.arange(12).reshape([4,3]),
               index=['a','b','c','d'],
               columns=columnas)
print(df)
#Vamos a utilizar el metodo loc para crear el rango de valores mediante
#el uso de las etiquetas de las filas
# df.loc[rango_etiquetas_filas,rango_etiquetas_columnas]=Valores
df.loc['b':'c','A':'B']=[[-1,-2],[-3,-4]]
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11


A   B   C
a  0   1   2
b -1  -2   5
c -3  -4   8
d  9  10  11

In [107]:
#ASignar unos valores a un rango de filas y columnas en el dataframe
columnas=['A','B','C']
df=pd.DataFrame(np.arange(12).reshape([4,3]),
               index=['a','b','c','d'],
               columns=columnas)
print(df)
#Vamos a utilizar el metodo loc para crear el rango de valores mediante
#el uso de las etiquetas de las filas
# df.loc[rango_etiquetas_filas,rango_etiquetas_columnas]=Valores
df.loc['b':'c','A':'B']=-1
df

   A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11


A   B   C
a  0   1   2
b -1  -1   5
c -1  -1   8
d  9  10  11