In [81]:
from numpy import random as r
print(r.choice(['Andres','Juan','Pedro','Mateo'], size=r.choice([1,2])))

['Andres' 'Andres']


In [82]:
import numpy as np
a=np.array([34,25,7])
print(a)
print(type(a))

[34 25  7]
<class 'numpy.ndarray'>


In [83]:
#La funcion shape me permite ver la dimension de una matriz
print(a.shape)

(3,)


In [84]:
print(a[0],a[1],a[2])

34 25 7


In [85]:
a[0]=4
print(a)

[ 4 25  7]


In [88]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print()
print(b.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [90]:
#PAra acceder a un elemento en una matriz de dos dimensiones
# b[índice_fila,indice_columna]
print(b[0,0])
print(b[0,1])
print(b[1,0])

1
2
4


In [92]:
#Crear una  matriz de ceros
import numpy as np
matriz=np.zeros((3,3))
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [93]:
#Crear una  matriz de unos
import numpy as np
matriz=np.ones((2,3))
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]]


In [94]:
#Crear una  matriz de una dimension especifica, y un valor constante
import numpy as np
matriz=np.full((2,3),9)
print(matriz)

[[9 9 9]
 [9 9 9]]


In [95]:
#Matriz identidad, es aquella matriz que si yo la multiplico por otra matriz, 
#el resultado va a ser igual a la misma matriz
#Matriz de identidad es una matriz cuadrada
#Matriz de identidad esta compuesta por valores de cero, en donde unicamente la diagonal
#principal son valores de 1
# A(3x3)*I(3x3)=A(3x3)
d=np.eye(8)
print(d)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [97]:
#Va a crear una matriz  de una dimension especifica con valores aleatorios 
#los valores aleatorios van a ser entre 0 y 1
e=np.random.random((4,5))
print(e)

[[0.7332078  0.73968463 0.98639131 0.50318527 0.10899008]
 [0.87195286 0.49917137 0.38629634 0.37127333 0.49328868]
 [0.94886997 0.43426855 0.852724   0.88380428 0.33122158]
 [0.24571414 0.9601415  0.44527336 0.130285   0.21857147]]


In [98]:
import numpy as np
a=np.array([[1,2,3],[5,6,7],[9,10,11]])
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [108]:
print(a)
#Puedo voltear la matriz con la funcion fliplr
print()
print(np.fliplr(a))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 3  2  1]
 [ 7  6  5]
 [11 10  9]]


In [106]:
#Utilizar la rebanada en matriz multidimensional
# a[indice_fila,indice_columna]
#Aqui solamente imprime la fila 0, y la fila 1
# b=a[:2,:]
# print(b)

#Aqui solamente imprime la columna 1, y la columna 2
# b=a[:,1:3]
# print(b)

#Aqui solamente imprime la fila 0, fila 1, columna 1, y la columna 2
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [111]:
print(a)
print()
print(a[0,1])
print()
#b es una rebanada de a
print(b)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

2

[[2 3]
 [6 7]]


In [113]:
#Si una rebanada de una matriz original es modificada, inmediamente
#la matriz original tambien es modificada
b[0,0]=77
print(a)

[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


In [119]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [120]:
#Manejo de filas en una matriz
row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [123]:
#Manejo de columnas en una matriz con numeros enteros
print(a)
print()
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [128]:
#indexacion de matrices con enteros
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print()
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)


In [129]:
# a[[indices_filas],[indices_columnas]]
print(a[[0,1,2],[0,1,1]])

[1 4 6]


In [130]:
print(np.array([a[0,0],a[1,1],a[2,1]]))

[1 4 6]


In [132]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)

#Creamos una matriz de indices
b=np.array([0,2,0,1])
print('\n',b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 [0 2 0 1]


In [135]:
# a[[indices_filas],[indices_columnas]]
# arange(start, stop, step)
#Start hace referencia desde donde empieza a contar
#stop hace referencia hasta donde llega, pero no incluye este valor
#step hace referencia a los saltos
# arange(0,10,2)
# [0,2,4,6,8]

# a[[0,1,2,3],[0,2,0,1]]
print(a)
print()
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]


In [137]:
#HE modificado un valor de una matriz a partir 
#de la indexacion de matrices con enteros
a[np.arange(4),b]+=10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [139]:
#Indexacion de matriz booleana
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print()
bool_idx=(a>2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]


In [140]:
print(a[bool_idx])

[3 4 5 6]


In [141]:
print(a[a>2])

[3 4 5 6]


In [143]:
#Tipos de datos entero
import numpy as np
x=np.array([1,2])
print(x.dtype)

int64


In [144]:
#Tipos de datos flotante
import numpy as np
x=np.array([1.0,2.0])
print(x.dtype)

float64


In [149]:
#Tipos de datos flotante, tenga datos enteros
import numpy as np
x=np.array([1.08,2.40], dtype=np.int64)
print(x.dtype)
print(x)

int64
[1 2]


In [150]:
#Operaciones matematicas
#Suma
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x,'\n')
print(y)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]


In [151]:
print(x+y)
print()
print(np.add(x,y))

[[ 6  8]
 [10 12]]

[[ 6  8]
 [10 12]]


In [154]:
#resta de matrices, elemento a elemento
print(x,'\n')
print(y)
print(x-y)
print()
print(np.subtract(x,y))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]

[[-4 -4]
 [-4 -4]]


In [156]:
#multiplicacion de matrices, elemento a elemento
print(x,'\n')
print(y,'\n')
print(x*y)
print()
print(np.multiply(x,y))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]


In [157]:
#division de matrices, elemento a elemento
print(x,'\n')
print(y,'\n')
print(x/y)
print()
print(np.divide(x,y))

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [159]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

v=np.array([9,10])
w=np.array([11,12])

In [162]:
#Producto punto interno vectores v y w
#Puedo utilizar una funcion interna de python .dot
print((9*11)+(10*12))
print()

print(v.dot(w))
#puedo utilizar .dot de la libreria de numpy
print(np.dot(v,w))

219

219
219


In [163]:
#Producto punto entre la matriz x y la matriz v
print(x,'\n')
print(v,'\n')
print(x.dot(v))

[[1 2]
 [3 4]] 

[ 9 10] 

[29 67]


In [166]:
#Funcion sum de numpy
import numpy as np
x=np.array([[1,2],[3,4]])
print(x,'\n')
print(np.sum(x),'\n')
print(np.sum(x, axis=0)) #Sumando los valores en la columna
print()
print(np.sum(x, axis=1)) #Sumando los valores en la filas


[[1 2]
 [3 4]] 

10 

[4 6]

[3 7]


In [167]:
#Transponer una matriz mediante el atributo T
import numpy as np
x=np.array([[1,2],[3,4]])
print(x,'\n')
print(x.T)

[[1 2]
 [3 4]] 

[[1 3]
 [2 4]]


In [170]:
#Transponer una matriz mediante el atributo T
#No puedo trasnponer una matriz de una sola dimension o de rango 1
import numpy as np
x=np.array([1,2,3,4])
print(x,'\n')
print(x.T)

[1 2 3 4] 

[1 2 3 4]


In [173]:
#Broadcasting
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x) #Crea una matriz vacia con la misma forma que x
print(x,'\n')
print(y,'\n')
print(v,'\n')

#Puedo sumar el vector v a cada fila de la matriz x mediante un bucle for
# [0,1,2,3]
for i in range(4):
    y[i,:]=x[i,:]+v
    
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[1 0 1] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [177]:
#Broadcasting
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
vv=np.tile(v,(4,1)) #Funcion tile permite amontonar 4 veces el vector v uno encima de otro
print(x,'\n')
print(vv,'\n')

#Puedo sumar la matriz x con la matriz vv
y=x+vv
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]] 

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [180]:
#Broadcasting usando transmision
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([[1,0],[3,0]])

print(v,'\n')
print(np.sum(v,axis=0))
print(3 in np.sum(v,axis=0))
print(4 in np.sum(v,axis=0))

[[1 0]
 [3 0]] 

[4 0]
False
True


In [183]:
#Ejemplo del broadcasting
import numpy as np
v=np.array([1,2,3])
w=np.array([4,5])
print(v,'\n')
print(w,'\n')

[1 2 3] 

[4 5] 



In [187]:
print(np.reshape(v,(3,1)))
print('\n',w)
print()
print(np.reshape(v,(3,1))*w)

[[1]
 [2]
 [3]]

 [4 5]

[[ 4  5]
 [ 8 10]
 [12 15]]


In [192]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print('\n',v)
print()
#X(2x3)  y V(1*3)
print(x+v)

[[1 2 3]
 [4 5 6]]

 [1 2 3]

[[2 4 6]
 [5 7 9]]


In [197]:
#Cuando voy a realizar la suma de dos matrices elementos a elemento
#Debo tener en cuenta, que ambas matrices deben tener la misma dimension en las columnas
#W(1x2)  x(2*3)
print(w)
print(x)
print()
#x(3x2)
print(x.T)
print()
print((x.T+w).T)

[4 5]
[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[ 5  6  7]
 [ 9 10 11]]


In [200]:
#Cuando voy a realizar la suma de dos matrices elementos a elemento
#Debo tener en cuenta, que ambas matrices deben tener la misma dimension en las columnas
#W(1x2)  x(2*3)
print(w)
print(x)
a=np.reshape(w,(2,1))
print(a)
print()
print(x+np.reshape(w,(2,1))) #Reshape tambien permite transponer un vector

[4 5]
[[1 2 3]
 [4 5 6]]
[[4]
 [5]]

[[ 5  6  7]
 [ 9 10 11]]
