In [33]:
from numpy import random as r

print(r.choice(['Andres','Juan','Pedro','Mateo'], size=r.choice([1,3])))


['Andres' 'Andres' 'Juan']


In [42]:
import numpy as np
a=np.array([34,25,7])
print(a)
print(type(a))

[34 25  7]
<class 'numpy.ndarray'>


In [36]:
print(a.shape)

(3,)


In [43]:
a[0]

34

In [44]:
a[0]=5
print(a)

[ 5 25  7]


In [40]:
a[1]

array([4, 5, 6])

In [45]:
import numpy as np
b=np.array([[34,25,7],[4,5,6]])
print(b)
print(b.shape)

[[34 25  7]
 [ 4  5  6]]
(2, 3)


In [48]:
print(b[0,0])
print(b[1,1])
print(b[1,2])

34
5
6


In [50]:
#Matriz de ceros
import numpy as np
matriz=np.zeros((3,3))
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [51]:
#Matriz de unos
import numpy as np
matriz=np.ones((2,3))
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]]


In [55]:
#Matriz de una dimension especifica con un numero constante
import numpy as np
matriz=np.full((2,3),9)
print(matriz)

[[9 9 9]
 [9 9 9]]


In [56]:
#MAtriz de identidad multiplicada por otra matriz A, el resultado va ser la matriz A
# A(3x3)*I(3*3)=A(3x3)
# A*1=A
#Una matriz identidad tiene como caracteristca que todos sus elementos es igual a 0, 
#escepto la diagonal principal desde el eje izquierdo hasta el derecho
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [57]:
d=np.eye(8)
print(d)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [58]:
#Crear una matriz con valores aleatorios
e=np.random.random((2,3))
print(e)

[[0.98825775 0.88116504 0.43121442]
 [0.18922834 0.19582823 0.45316724]]


In [60]:
#Rebanada o slicing en una matriz
import numpy as np

a=np.array([[1,2,3],[5,6,7],[9,10,11]])
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [70]:
#Rebanada slicing
# b[fila, columnas]
c=a[0:2,1:]
print(c)

[[2 3]
 [6 7]]


In [62]:
#Rebanada slicing
# b[fila, columnas]
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [75]:
#Una rebanada de una matrizz es una vista en los mismos datos de la matriz original
#por lo tanto modificar la rebanada tambien modifica la matriz original
print(a[0,1])

2


In [76]:
print(b[0,0])

2


In [79]:
#Modificar la rebanada de una matriz, tambien modifica
#la matriz original
b[0,0]=77
print(b[0,0])
print(a)

77
[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


In [73]:
#La funcion fliplr me permite voltear los valores en una matriz de derecha a izquierda
print(a)
print()
print(np.fliplr(a))

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]

[[ 3  2  1]
 [ 7  6  5]
 [11 10  9]]


In [84]:
#Indexacion de filas con enteros
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print()
row_r1=a[1,:]
row_r2=a[1:2,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [88]:
#Indexacion de columnas con enteros
import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print()
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1, col_r1.shape, type(col_r1))
print(col_r2, col_r2.shape, type(col_r2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[ 2  6 10] (3,) <class 'numpy.ndarray'>
[[ 2]
 [ 6]
 [10]] (3, 1) <class 'numpy.ndarray'>


In [95]:
#Indexacion de matrices con enteros
import numpy as np

a=np.array([[1,2],[5,6],[9,10]])
print(a)
print()

#LE estoy pasando un lista de indices de la fila  y otra lista con los indices de la columna
# a[[indices de las filas],[indices de las columnas]]


# print(a[[0,1,2],[0,1,0]])
print(a[[0,1,2],[0,0,1]])
print()
print(a.shape)

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[ 1  5 10]

(3, 2)


In [96]:
print(np.array([a[0,0],a[1,1]]))

[1 6]


In [98]:
a[2,1]

10

In [100]:
# arange(start, stop, step)
# arange(0,10,2)
#START; El valor de cero desde donde va a empezar, 
#STOP; El valor 10, hasta donde va a a llegar, el 10 no se toma, osea desde 0 a 9
# [0,1,2,3,4,5,6,7,8,9]
#Step, son los saltos que va tomar para generar el arreglo
# [0,2,4,6,8]

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b=np.array([0,2,0,1])
print()
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[0 2 0 1]


In [103]:
#LE estoy pasando un lista de indices de la fila  y otra lista con los indices de la columna
# a[[indices de las filas],[indices de las columnas]]
# a[[0,1,2,3],[0,2,0,1]]
print(a)
print()
print(a[np.arange(4),b])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]


In [105]:
#HE modificado los valores de la matriz
a[np.arange(4),b]+=10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [107]:
# Indexacion de matriz booleana

import numpy as np

a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print()
bool_idx=(a>2)
print(bool_idx)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[False False  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [110]:
#Crea un arreglo con los elementos que cumplan la condicion a>2
print(a[bool_idx])

[ 3  4  5  6  7  8  9 10 11 12]


In [111]:
#Crea un arreglo con los elementos que cumplan la condicion a>2
print(a[a>2])

[ 3  4  5  6  7  8  9 10 11 12]


In [112]:
#TIPOS DE DATOS
import numpy as np
x=np.array([1,2])
print(x.dtype)

int64


In [113]:
#TIPOS DE DATOS
import numpy as np
x=np.array([1.0,2.0])
print(x.dtype)

float64


In [115]:
#TIPOS DE DATOS
import numpy as np
x=np.array([1.05,2.0543], dtype=np.int64)
print(x.dtype)
print(x)

int64
[1 2]


In [118]:
#Operaciones con matrices
import numpy as np

a=np.array([[1,2],[3,4]],dtype=np.float64)
b=np.array([[5,6],[7,8]],dtype=np.float64)
print(a,'\n')
print(b)

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]]


In [121]:
#Suma con matrices, suma elemento a elemento
print(a+b)
print()
print(np.add(a,b))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [125]:
#Resta con matrices, resta elemento a elemento
print(a,'\n')
print(b,'\n')
print(a-b)
print()
print(np.subtract(a,b))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [127]:
#multiplicacion con matrices, multiplica elemento a elemento
print(a,'\n')
print(b,'\n')
print(a*b)
print()
print(np.multiply(a,b))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [128]:
#Division con matrices, divide elemento a elemento
print(a,'\n')
print(b,'\n')
print(a/b)
print()
print(np.divide(a,b))

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [129]:
#Raiz cuadrada con matrices, 
print(a,'\n')
print(np.sqrt(a))

[[1. 2.]
 [3. 4.]] 

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [135]:
import numpy as np

x=np.array([[1,2],[3,4]],dtype=np.int64)
y=np.array([[5,6],[7,8]],dtype=np.int64)
print(a,'\n')
print(b)

[ 9 10] 

[11 12]


In [138]:
#Dos formas de hallar el producto punto de dos matrices
print(x.dot(y))
print()
print(np.dot(x,y))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [133]:
import numpy as np

a=np.array([9,10])
b=np.array([11,12])
print(a,'\n')
print(b)

print(a.dot(b))
print(np.dot(a,b))

[ 9 10] 

[11 12]
219
219


In [ ]:
# [9,10][11,12]= (9*11)+(10*12)=99+120=219

In [143]:
#Funcion sum en numpy
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print()

print(np.sum(x))
print(np.sum(x, axis=0)) #Suma los valores de la columna
print(np.sum(x, axis=1)) #Suma los valores de la fila

[[1 2]
 [3 4]]

10
[4 6]
[3 7]


In [146]:
#Transponer una matriz
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print()

print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [148]:
#Transponer una matriz
#No podemos trasnponer una matriz de una sola dimension
import numpy as np
y=np.array([1,2,3])
print(y)
print()

print(y.T)

[1 2 3]

[1 2 3]


In [151]:
#Broadcasting

import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x) #Crear una matriz vacia con la misma forma de x
print(x)
print()
print(v)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [153]:
#Añadir el vector v a cada fila de la matriz x con un bucle for
for i in range(4):
    y[i,:]=x[i,:]+v
print(x)
print()
print(v)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [155]:
#Broadcasting

import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
#Tile me permite amontonar 4 veces el vector v, uno encima de otro
vv=np.tile(v,(4,1))
print(x)
print()
print(v)
print()
print(vv)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [156]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [161]:
#Broadcasting

import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([[1,0],[3,0]])
print(v)
print()
#De la matriz V, sume las columnas y verifique si una suma es equivalente a 3
print(3 in np.sum(v, axis=0))
print(4 in np.sum(v, axis=0))

[[1 0]
 [3 0]]

False
True


In [167]:
import numpy as np

v=np.array([1,2,3])
w=np.array([4,5])

print(v)
print()
print(w)

vv=np.reshape(v,(3,1))
print(vv)
print()
y=vv*w
print(y)

[1 2 3]

[4 5]
[[1]
 [2]
 [3]]

[[ 4  5]
 [ 8 10]
 [12 15]]


In [171]:
x=np.array([[1,2,3],[4,5,6]])
print(x)
print()
print(v)
print()

print(x+v)

[[1 2 3]
 [4 5 6]]

[1 2 3]

[[2 4 6]
 [5 7 9]]


In [175]:
print(x.T)
print()
print(w)
print((x.T+w).T)

[[1 4]
 [2 5]
 [3 6]]

[4 5]
[[ 5  6  7]
 [ 9 10 11]]


In [178]:
print(x)
print()
print(w)
print()
print(np.reshape(w,(2,1)))
print()
print(x+np.reshape(w,(2,1)))

[[1 2 3]
 [4 5 6]]

[4 5]

[[4]
 [5]]

[[ 5  6  7]
 [ 9 10 11]]
