In [23]:
# lista=[1,3,4,5]
# print(lista)
lista=[[1,2,3,4],[4,6,7,8],[9,10,11,12]]
print(lista)

[[1, 2, 3, 4], [4, 6, 7, 8], [9, 10, 11, 12]]


[1,2,3,4]

[4,6,7,8]

[1,5,6,2]

In [22]:
from numpy import random as r
#Funcion choice de numpy me permite eligir de una lista o una matriz un elemento aleatoriamente
#Funcion size me permite indicar el arreglo que quiero obtener, en este caso una matriz de 1x2
print(r.choice(['Andres','Juan','Pedro','Mateo'],size=r.choice([1,2])))

['Mateo' 'Pedro']


In [13]:
import numpy as np
a=np.array([34,25,7])
print(a)
print(type(a))

[34 25  7]
<class 'numpy.ndarray'>


In [14]:
print(a.shape)

(3,)


In [16]:
print(a[0])
print(a[1])
print(a[2])

34
25
7


In [20]:
#Como puedo cambiar el valor en una matriz
a[0]=5
print(a)

[ 5 25  7]


In [18]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [19]:
#Puedo mirar la dimension de mi matriz con la funcion shape
b.shape

(2, 3)

In [25]:
#Metodo array es una funcion que permite crear una matriz
b=np.array([[1,2,3],[4,5,6]])
print(b)
print()
print(b.shape)

[[1 2 3]
 [4 5 6]]

(2, 3)


In [31]:
#Accediendo a los elementos de una lista en la matriz
print(b[0,0])
print(b[0,1])
print(b[1,0])

1
2
4


In [27]:
lista=[1,3,4,5]
print(lista[0])

1


In [32]:
#Creando una matriz de ceros con el metodo ZEROS
import numpy as np
matriz=np.zeros((3,3))
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [33]:
#Creando una matriz de ones con el metodo ONES
import numpy as np
matriz=np.ones((2,3))
print(matriz)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#Creando una matriz de una dimension especifica con valores 
#constantes, en este caso 7
import numpy as np
matriz=np.full((2,3),8)
print(matriz)

[[8 8 8]
 [8 8 8]]


# Matriz identidad

Cualquier matriz que yo multiple por una matriz identidad, voy a obtener la misma matriz.

A(3x3)*I(3x1)=A(3x1)

# Multiplicacion de matrices

### OJO IMPORTANTE TENER EN CUENTA

Cuando multiplicamos dos matrices, debemos tener en cuenta que el numero de **columnas** de la matriz A, es igual al numero de **filas** de la matriz B. 

A(3x3)*B(3*2)=C(3x2)  

In [37]:
#Crear una matriz identidad, siempre va a ser una matriz cuadrada
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [38]:
#Crear matriz con valores aleatorios
e=np.random.random((2,3))
print(e)

[[0.30418621 0.14719448 0.67049464]
 [0.78362482 0.82277274 0.85309753]]


In [39]:
import numpy as np
a=np.array([[1,2,3],[5,6,7],[9,10,11]])
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [43]:
# b=[slicing_filas,slicing_columnas]
b=a[:2,1:]
print(b)

[[2 3]
 [6 7]]


In [45]:
#Una rebanada de una matriz es una vista de la matriz original
#modificarla, tambien modifica la matriz original
print(a[0,1])

2


In [46]:
b[0,0]=77
print(a[0,1])
print(a)

77
[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


In [44]:
#Esta funcion me permite invertir los valores en una matris
#de tal forma que el primer valor en la izquierda pasa de ultimo y el ultimo 
#valor pasa de primero
print(np.fliplr(a))

[[ 3  2  1]
 [ 7  6  5]
 [11 10  9]]


In [47]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [57]:
#Accediendo a las filas de una matriz
row_r1=a[1,:]
row_r2=a[1:3,:]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)


In [59]:
#Accediendo a las columnas de una matriz
row_r1=a[:,1]
row_r2=a[:,1:2]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [64]:
#Indexacion de matrices de enteros
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)
# print(a[[ind_listas_matriz],[indi_elemen_lista]])
print(a[[0,1,2],[0,1,0]])

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[1 4 5]


In [65]:
#La indexacion de arreglos anterior es similar a decir lo siguiente
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [66]:
print(a[[0,0],[1,1]])

[2 2]


In [68]:
# arange(start, stop, step)
np.arange(1,10,3)

array([1, 4, 7])

In [75]:
import numpy as np

# Crear una nueva matriz de la cual seleccionaremos elementos
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
# Crear una serie de índices
b = np.array([0, 2, 0, 1])

#arange me va crear el sgte arreglo [0,1,2,3]
# Selecciona un elemento de cada fila de a usando los índices de b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [79]:
#He modificado o mutado mi matriz mediante una indexacion de arreglos
a[np.arange(4), b]+=10
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [80]:
#indexacion con matrices booleanas
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
bool_idx=(a>2)
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [81]:
print(a[bool_idx])

[3 4 5 6]


In [82]:
print(a[a>2])

[3 4 5 6]


In [84]:
#Tipos de datos de  una matrix
import numpy as np
x=np.array([1,2])
print(x.dtype)

int64


In [85]:
x=np.array([1.0,2.0])
print(x.dtype)

float64


In [87]:
x=np.array([1.7,2.6],dtype=np.int64)
print(x)
print(x.dtype)

[1 2]
int64


In [90]:
#Operaciones matematicas sobre matrices
import numpy as np
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print(x)
print()
print(y)


[[1. 2.]
 [3. 4.]]

[[5. 6.]
 [7. 8.]]


In [92]:
#Suma de elementos, ambos produce una matriz c con la sma elementos por elemento
#de ambas matrices
print(x+y)
print()
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [95]:
#Restar  matrices
print(x-y)
print()
print(np.subtract(x,y))


[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


In [96]:
#Mutiplicacion entre matrices
print(x*y)
print()
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [97]:
#division entre matrices
print(x/y)
print()
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [103]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x)
print()
print(y)

v=np.array([9,10])
w=np.array([11,12])
print()
print(v)
print()
print(w)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[ 9 10]

[11 12]


In [104]:
# (9*11)+(10*12)=219

print(v.dot(w))
print()
print(np.dot(v,w))

219

219


In [105]:
print(x.dot(y))
print()
print(np.dot(x,y))

[[19 22]
 [43 50]]

[[19 22]
 [43 50]]


In [108]:
import numpy as np
x=np.array([[1,2],[3,4]])
print(np.sum(x))
print()
print(x)
print()
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

10

[[1 2]
 [3 4]]

[4 6]
[3 7]


In [110]:
#Tranponer una matriz
import numpy as np
x=np.array([[1,2],[3,4]])
print(x)
print()
print(x.T)

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


In [117]:
#Broacasting
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
v=np.array([1,0,1])
y=np.empty_like(x)
print()
print(v)
print()
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [115]:
for i in range(4):
    y[i,:]=x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [120]:
#Broacasting
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(x)
v=np.array([1,0,1])
vv=np.tile(v,(4,1))
print()
print(v)
print()
print(vv)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[1 0 1]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [121]:
y=x+vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [137]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([[1,0],[3,0]])
print(x)
print()
print(v)
print()
#Verifica si el 3 se encuentra en la suma del vector v
print(3 in np.sum(v,axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 0]
 [3 0]]

False


In [128]:
y=x+v
print(y)

ValueError: operands could not be broadcast together with shapes (4,3) (2,2) 

In [129]:
import numpy as np

# Calcular el producto exterior de los vectores
v = np.array([1,2,3]) # v tiene forma (3,)
w = np.array([4,5]) # w tiene forma (2,)
# Para calcular un producto exterior, primero reformamos v para que sea una columna
# vector de forma (3, 1); podemos entonces emitirlo contra w para rendir
# una salida de la forma (3, 2), que es el producto exterior de v y w:
# [[ 4 5]
# [ 8 10]
# [12 15]]
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [144]:
import numpy as np

# Calcular el producto exterior de los vectores
v = np.array([1,2,3]) # v tiene forma (3,)
w = np.array([4,5]) # w tiene forma (2,)
# Para calcular un producto exterior, primero reformamos v para que sea una columna
# vector de forma (3, 1); podemos entonces emitirlo contra w para rendir
# una salida de la forma (3, 2), que es el producto exterior de v y w:
# [[ 4 5]
# [ 8 10]
# [12 15]]
# print(np.reshape(v, (3, 1)))
z=np.reshape(v, (3, 1))
print()
print(w)
print()
print(z)
a=z*w
print(a)


[4 5]

[[1]
 [2]
 [3]]
[[ 4  5]
 [ 8 10]
 [12 15]]


In [131]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)
b=np.reshape(a,(4,3))
print(b.shape)
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
