In [1]:
#Variables, es un unidad de almacenamiento de datos que pueden ser numeros enteros
#numeros flotantes, cadena de texto (string), datos booleanos
entero=10
flotante1=20.45
flotante2=10/3
cadena='Hola mundo'
booleano=True #False

#La funcion permite imprimir un valor o un mensaje en pantalla
print(entero)
print(flotante1)
print(flotante2)
print(cadena)
print(booleano)

10
20.45
3.3333333333333335
Hola mundo
True


In [7]:
#Imprimir mensajes en la pantalla mediante la funcion print de python
nombre='Brayan'
edad=19
altura=1.75
#Formateo de texto mediante el operador de %
#Para un string vamos a manejar la letra s
#Para un flotante vamos a manejar la letra f
#para un entero vamos a manejar la letra d
print("Hola, bienvenido %s, tu tienes %d años, y tu altura es: %f" %(nombre,edad, altura) )
print()
print("Hola, bienvenido {}, tu tienes {} años, y tu altura es: {}".format(nombre,edad, altura)) 
print()
print("Hola, bienvenido ",nombre," tu tienes ",edad," años, y tu altura es: ",altura)
print()
#Siempre los datos de tipo string van a ir entre comilla simple o comilla doble

print("Hola, bienvenido "+nombre+" tu tienes ",edad," años, y tu altura es: ",altura)

Hola, bienvenido Brayan, tu tienes 19 años, y tu altura es: 1.750000

Hola, bienvenido Brayan, tu tienes 19 años, y tu altura es: 1.75

Hola, bienvenido  Brayan  tu tienes  19  años, y tu altura es:  1.75

Hola, bienvenido Brayan tu tienes  19  años, y tu altura es:  1.75


In [11]:
#Python detecta entre mayusculas y minusculas
var=9
VAR='hola'
print(var)
print(VAR)

9
hola


In [17]:
#Colecciones de datos
#Las listas van definidas por unos elementos separados por coma entre corchetes, 
#Las listas pueden contener cualquier tipo de datos
listas=[1,'Hola',3.45,True,[1,2]]
print(listas)
#La funcion len permite contabilidad cuantos elementos tiene una coleccion de datos o variable
len(listas)
print(listas[0])
print(listas[1])
print(listas[4])
#Accedo a una lista interna dentro de otra lista
print(listas[4][1])

[1, 'Hola', 3.45, True, [1, 2]]
1
Hola
[1, 2]
2


In [19]:
#Las listas son mutables, por lo tanto sus valores pueden ser modificados, añadir 
#nueevos elementos
#para cambiar un valor, solo basta con  acceder al elemento mediante el indice o la 
#posicion en que se encuentra en la lista y asignar un nuevo valor
listas[4]=False
print(listas)

[1, 'Hola', 3.45, True, False]


In [25]:
#Puedo utilizar len() para mirar el tamaño de un elemento, en este caso una lista
print(len(listas))
#Acceder al ultimo elemento de la lista
print(listas[len(listas)-1])
#Tambien manejando esta logica, en python se puede resumir de la siguiente forma
print(listas[-1])
#Acceder al penultimo elemento de la lista
print(listas[-2])

#Nosotros podemos concluir, que para recorrer una lista de izquierda a derecha
#utilizamos los indices desde la posicion 0, hasta una posicion n, donde n es el 
#tamño de la lista-1
#Podemos recorrer una lista de derecha a izquierda, desde la posicion -1, luego -2 y asi sucesivamente

5
False
False
True


In [26]:
#Las listas tienen unos metodos que permiten manejar la informacion en esa estructura de datos
#Puedo utilizar la funcion dir() para ver los metodos de una lista
dir(listas)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [28]:
lista=[1,2,3,4,5,6,7]
print(lista)
#Metodo append para añadir un valor a la lista
lista.append(8)
print(lista)

[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]


In [29]:
lista=[6,4,7,2,4,56,8,1,3,4,56,67,74,3,1]
print(lista)
#Metodo sort() que me permite ordenar una lista de forma ascendente
lista.sort()
print(lista)

[6, 4, 7, 2, 4, 56, 8, 1, 3, 4, 56, 67, 74, 3, 1]
[1, 1, 2, 3, 3, 4, 4, 4, 6, 7, 8, 56, 56, 67, 74]


In [30]:
#Puedo ordenar de mayor a menor, es decir descendente
lista.sort(reverse=True)
print(lista)

[74, 67, 56, 56, 8, 7, 6, 4, 4, 4, 3, 3, 2, 1, 1]


In [31]:
#Una lista de caracteres, va a ordenar de forma alfabetica
lista=['z','f','e','a','j','s','b']
print(lista)
#Metodo sort() que me permite ordenar una lista de forma ascendente
lista.sort()
print(lista)

['z', 'f', 'e', 'a', 'j', 's', 'b']
['a', 'b', 'e', 'f', 'j', 's', 'z']


In [37]:
#Tuplas
#Las tuplas son elementos inmutables, es decir no podemos modificar valores
tupla1=1,'hola',2,3,True
print(tupla1)

#Tuplas
#Las tuplas son elementos inmutables, es decir no podemos modificar valores
tupla2=(1,'hola',2,3,True)
print(tupla2)

#LAs tuplas manejan indices, en el cual, el primer elemento esta en el indice 0
print(tupla1[0])
print(tupla1[4])

(1, 'hola', 2, 3, True)
(1, 'hola', 2, 3, True)
1
True


In [38]:
#Las tuplas no puede modificar sus valores
tupla1[4]=False

TypeError: 'tuple' object does not support item assignment

In [39]:
dir(tupla1)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [42]:
tupla2=(1,'hola',2,3,True,2,2)
print(tupla2)
#La funcion count permite saber cuantas veces esta repetido un elemento en la tupla
tupla2.count(2)

(1, 'hola', 2, 3, True, 2, 2)


3

In [45]:
#Diccionarios
#Los diccionarios tienen una estructura de elementos conformados por parejas clave-valor 
diccionario={'clave1':132,'clave2':'Hola','clave3':2.34}
print(diccionario)

#Los diccionario no manejan indices, para acceder a un valor lo hacemos por medio de la clave
#Los diccionarios son mutable, se peuden modificar
#Pueden contener cualquier tipo de elemento
print(diccionario['clave2'])
print(diccionario['clave3'])

{'clave1': 132, 'clave2': 'Hola', 'clave3': 2.34}
Hola
2.34


In [47]:
#Puedo modificar un diccionario, voy a cambiar un valor de una clave
diccionario['clave3']=True
print(diccionario)

{'clave1': 132, 'clave2': 'Hola', 'clave3': True}


In [48]:
#Añadir una pareja clave valor a un diccionario
diccionario['clave4']=[1,2,3]
print(diccionario)

{'clave1': 132, 'clave2': 'Hola', 'clave3': True, 'clave4': [1, 2, 3]}


In [49]:
dir(diccionario)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [63]:
#Los diccionario no manejan indices
diccionario[0]

KeyError: 0

In [60]:
print(diccionario)
print()
#Funcion keys devuelve las claves del diccionario
key=diccionario.keys()
print(key)
print()
#Funcion values devuelve los valores del diccionraio
valores=diccionario.values()
print()
print(valores)
#Funcion items que me devuelve la pareja clave-valor en una tupla
print()
item=diccionario.items()
print(item)

{'clave1': 132, 'clave2': 'Hola', 'clave3': True, 'clave4': [1, 2, 3]}

dict_keys(['clave1', 'clave2', 'clave3', 'clave4'])


dict_values([132, 'Hola', True, [1, 2, 3]])

dict_items([('clave1', 132), ('clave2', 'Hola'), ('clave3', True), ('clave4', [1, 2, 3])])


In [61]:
print(type(item))

<class 'dict_items'>


In [59]:
#Convertir estos arreglos en una lista utilizando la funcion list
key=list(key)
valor=list(valores)
item=list(item)
print(key)
print(valor)
print(item)
print()
item[1]

['clave1', 'clave2', 'clave3', 'clave4']
[132, 'Hola', True, [1, 2, 3]]
[('clave1', 132), ('clave2', 'Hola'), ('clave3', True), ('clave4', [1, 2, 3])]



('clave2', 'Hola')

In [65]:
#Convertir una tupla en una lista
tupla=(3,4,5,6)
print(tupla)
lista=list(tupla)
print(lista)

(3, 4, 5, 6)
[3, 4, 5, 6]


In [68]:
#Conjunto
#Los conjuntos son colecciones de datos que no permiten elementos mutables en sus datos
#los conjuntos no admiten elementos repetidos y no manejan indices
conjunto={1,2,3,4,'hola',True,2,2,2,2,2,2}
print(conjunto)

{1, 2, 3, 4, 'hola'}


In [70]:
#Estructuras de control 

#Condiccional if: este condicional me permite evaluar si una condicion es verdadera
#toma un camino, y si la condicion es falsa toma otro camino
var=101
if var==10: 
    print("Hola, bienvenido")
else:
    print("Adios")

Adios


In [72]:
#Estructuras de control 

#Condiccional if: este condicional me permite evaluar si una condicion es verdadera
#toma un camino, y si la condicion es falsa toma otro camino
#En esta estructura de datos, si una condicion se cumple, ya no procede a evaluar las demas
#condiciones, solo se ejecuta una vez
var=11

if var<10: 
    print("Hola, bienvenidos")
elif var>10:
    print("Vas a realizar el parcial")
else:
    print("Adios")

Vas a realizar el parcial


In [73]:
#Estructuras de control 

#Condiccional if: este condicional me permite evaluar si una condicion es verdadera
#toma un camino, y si la condicion es falsa toma otro camino
#En esta estructura de datos, si una condicion se cumple, ya no procede a evaluar las demas
#condiciones, solo se ejecuta una vez
var=11
if var<10: 
    print("Hola, bienvenidos")
elif var>10:
    print("Vas a realizar el parcial")
    var=var+10  #var=var+=1
    print(var)
else:
    print("Adios")

Vas a realizar el parcial
21


In [78]:
#Estructuras de control 

#While, en un bucle que permite ejecutar una serie de instrucciones mientras que una 
#condicion sea verdadera, cuando la condicion es falsa, el bucle se termina
#El bucle while tiene una variable de iteracion que hace que la condicion en un momento
#sea falsa y el bucle termine, si no existe variable de iteracion se tiene un bucle infinito
var=11
while var>0:
    var-=1 #var=var-1
    print("La variable tiene un valor de: ",var)
print("Fin de la condicion")

La variable tiene un valor de:  10
La variable tiene un valor de:  9
La variable tiene un valor de:  8
La variable tiene un valor de:  7
La variable tiene un valor de:  6
La variable tiene un valor de:  5
La variable tiene un valor de:  4
La variable tiene un valor de:  3
La variable tiene un valor de:  2
La variable tiene un valor de:  1
La variable tiene un valor de:  0
Fin de la condicion


In [83]:
#Bucle for que me permite recorrer estructuras iterables por ejemplo una lista, un diccionario, una tupla

#Recorrer una lista
lista=[1,3,4,5,6,7,78,8,5]
# print(len(lista))

# range(start, stop, step)  ->  for x=0; x<10, x=x+1 (x++)
# [0,1,2,3,4,5,6,7,8,9]
for i in range(len(lista)):
    print(i, lista[i])

0 1
1 3
2 4
3 5
4 6
5 7
6 78
7 8
8 5


In [84]:
#Bucle for que me permite recorrer estructuras iterables por ejemplo una lista, un diccionario, una tupla

#Recorrer una lista
lista=[1,3,4,5,6,7,78,8,5]
# print(len(lista))

# i va a contener los valores de los elementos en la lista
for i in lista:
    print(i)

1
3
4
5
6
7
78
8
5


In [86]:
#Funcion enumerate en un for que permite obtener el indice y valor de una lista
lista=[1,3,4,5,6,7,78,8,5]
for indice, valor in enumerate(lista):
    print(indice, valor)

0 1
1 3
2 4
3 5
4 6
5 7
6 78
7 8
8 5


In [80]:
for i in range(0,10,2):
    print(i)


0
2
4
6
8


In [87]:
#Recorrer una tupla
tupla=(3,4,5,6,7,6)
for i in tupla:
    print(i)

3
4
5
6
7
6


In [88]:
#Recorrer una tupla
tupla=(3,4,5,6,7,6)
for i, valor in enumerate(tupla):
    print(i, valor)

0 3
1 4
2 5
3 6
4 7
5 6


In [91]:
#Recorramos un diccionario
diccionario={'clave1':132,'clave2':'Hola','clave3':2.34}
#Esta forma unicamente, me devuelve la clave
for i in diccionario:
    print(i, diccionario[i])

clave1 132
clave2 Hola
clave3 2.34


In [94]:
#Recorramos un diccionario
diccionario={'clave1':132,'clave2':'Hola','clave3':2.34}
#Esta forma unicamente, me devuelve la clave
lista=[]
for clave,valor in diccionario.items():
    print(clave, valor)
    lista.append((clave,valor))
    
print(lista)

clave1 132
clave2 Hola
clave3 2.34
[('clave1', 132), ('clave2', 'Hola'), ('clave3', 2.34)]


In [97]:
lista=[[1,2,3],[4,5,6],[7,8,9]]
print(lista)
#Accedo a la lista en el indice 1
print(lista[1])
#Acceder a la lista en el indice 2 y el valor de la lista en el indice 1
print(lista[2][1])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[4, 5, 6]
8


In [99]:
import numpy as np
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
#Acceder a los elementos de esta matriz de una forma similiar a una lista
# b[indice_fila, indice_columna]
b[1,2]

6

In [104]:
#Puedo acceder a los valores de la matriz mediante una indexacion de enteros
# print(b[[indices_filas],[indices_columnas]])
#Crear una array con la interseccion de las filas y columnas de una matriz
print(b[[0,2,1],[1,2,1]])

[2 9 5]
