In [3]:
from numpy import random as r
print(r.choice(['Andres','Juan','Pedro','Mateo'],size=r.choice([1,2],p=[0.1,0.9]),p=[0.5,0.2,0.2,0.1],replace=False))

['Mateo' 'Andres']


In [5]:
#Crear una matriz de rango 1
import numpy as np
a=np.array([34,25,7])
print(a)

[34 25  7]


In [6]:
type(a)

numpy.ndarray

In [7]:
print(a.shape)

(3,)


In [8]:
print(a[0],a[1],a[2])

34 25 7


In [10]:
#Cambiar un elemento de  una matriz
a[0]=5
print(a)

[ 5 25  7]


In [13]:
#Crear una matriz de rango 2
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
print(b.shape)

(2, 3)


In [16]:
#Encontrar valores de las matrices 
print(b[0,0],b[0,1],b[1,0])

1 2 4


# Funciones de matrices

In [18]:
#Crear una matriz de 3*3 llena de ceros
import numpy as np
matriz=np.zeros((3,3))
print(matriz)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
#Crear una matriz de 1*2 de unos,  un conjunto de todos ellos
import numpy as np
matriz=np.ones((1,2))
print(matriz)

[[1. 1.]]


In [24]:
#Crear una matriz constante de 2*2 con valores de 7
c=np.full((2,2),7)
print(c)

[[7 7]
 [7 7]]


In [26]:
#Crear una matriz de identidad 2*2
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [27]:
#Crear una matriz con valores aleatorios
e=np.random.random((2,2))
print(e)

[[0.48412007 0.2532602 ]
 [0.03056277 0.09136657]]


# Indexación de matrices
## Rebanar
Similar a las listas de python, las matrices de numpy se pueden cortat, matrices son multidimensionales, debe
especificar un segmento para cada dimension


In [74]:
import numpy as np
a=np.array([[1,2,3],[5,6,7],[9,10,11]])
print(a)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [75]:
#Usar la rebanada para sacar el subconjunto que consiste en las 2 primeras filas 
# y las columnas 1 y 2; b es el siguiente conjunto de forma (2,2)
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [76]:
#Usar la rebanada para sacar el subconjunto que consiste en las 2 primeras filas 
# y las columnas 1 y 2; b es el siguiente conjunto de forma (2,2)
c=a[1:2,1:3]
print(c)

[[6 7]]


In [77]:
#Cambiar posicion de los valores de una matriz, resultado matriz transversa
print(np.fliplr(a))

[[ 3  2  1]
 [ 7  6  5]
 [11 10  9]]


In [78]:
#una rebanada de una matriz es una vista en los mismos datos, por lo que modificarla, modificará 
#la matriz original
print(a[0,1])

2


In [80]:
b[0,0]

2

In [81]:
print(b)
b[0,0]=77
print(b)

[[2 3]
 [6 7]]
[[77  3]
 [ 6  7]]


In [83]:
print(a[0,1])
print(a)

77
[[ 1 77  3]
 [ 5  6  7]
 [ 9 10 11]]


In [84]:
#Indexacion de enteros con la idenxación de sectores. Al hacerlo, se obtendrá una matriz de rango más bajo 
# que la original. 
#Crear matriz de rango 2 con forma 3X4
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [87]:
#Dos formas de acceder a los datos de la fila del medio de la matriz,
#Mezclando la indexación de enteros con rebanadas se obtiene una matriz de rango inferior
#Mientras que usando solo rebanadas se obtiene un conjunto del mismo rango que el 
#La matriz original
row_r1=a[1,:] #rango 1 vista de la segunda fila de "a
print(row_r1) 
row_r2=a[1:2,:] #rango 2 vista de la segunda fila de "a
print(row_r2)

[5 6 7 8]
[[5 6 7 8]]


In [88]:
print(row_r1,row_r1.shape) 
print(row_r2,row_r2.shape) 

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [91]:
#podemos hacer la misma distincion al acceder a las columnas de una matriz
col_r1=a[:,1]
col_r2=a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


# Indexación de matrices de enteros
Cuando indexa matrices de números utilizando la división, la vista de matriz resultante siempre será una submatriz de la matriz original. Por el contrario, la indexación de matrices de enteros le permite construir matrices arbitrarias utilizando los datos de otra matriz. Aquí hay un ejemplo:

In [93]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [95]:
# Un ejemplo de indexación de arreglos enteros
# La matriz devuelta tendra una forma (3,2)
#Primer tupla fila, segunda tupla columna
print(a.shape)
print(a[[0,1,2],[0,1,0]])

(3, 2)
[1 4 5]


In [96]:
# Ejemplo anterior, la indexacion de arreglos enteros es equivalente a esto:
print(np.array([a[0,0],a[1,1],a[2,0]]))

[1 4 5]


In [98]:
#Cuando se usa la indexacion de arreglos a enteros, se puede reutilizar el mismo elemento
#de la matrix de la fuente
#Primer tupla fila, segunda tupla columna
print(a[[0,0],[1,1]])

[2 2]


In [99]:
# Ejemplo anterior, la indexacion de arreglos enteros es equivalente a esto:
print(np.array([a[0,1],a[0,1]]))

[2 2]
